### ISSUE TITLE
Importing images in CSS as background image gets [object Object].

### ISSUE THREAD

**Issue by timbergus** [EmilTholin/image-trace-loader#7]
Hi @EmilTholin,

I'm not sure if this is really a bug or that I don't know how to use the plugin, but despite it works fine when importing images in React, when I try to import images in CSS:

```css
main {
    background-image: url('~images/star.png');
}
```

The result I get in the developer's tools is that the content of the URL is an object:

```css
background-image: url([object Object]);
```

Is there any way to get in CSS the `src` of the image? Do I need to import images for CSS in a different way? How I can do it?

Thanks in advance.

Regard

**Comment by EmilTholin** [comment]
Hi @timbergus!

The reason why you get `[object Object]` in your CSS is because the result of importing an image with `image-trace-loader` is an object with a `src` and a `trace` property:

```javascript
import { src, trace } from './image.png';
```

The main use of `image-trace-loader` is to have the traced outline as a placeholder until the main image is loaded, just like in the [example in this repository](https://github.com/EmilTholin/image-trace-loader/tree/master/example).

If you are only interested in the trace, you could use it as an inline style in React instead:

```javascript
import { trace } from './image.png';

const MyComponent () => <div style={{ backgroundImage: `url(${trace})` }}></div>
```

**Comment by timbergus** [comment]
Thank @EmilTholin. Works great.

By the way. This plugin is amazing. Great job :)
